# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the mutual information
#'
#' Calculate the mutual information
#'
#' @param joint_dist A numeric matrix
#' @return The mutual information
#' @export
mutual_information <- function(joint_dist) {
    .Call(`_pacote4_mutual_information`, joint_dist)
}

